const { assert, createFakeDomElement, loadPlannerResultsModule } = require("./helpers.cjs");

function testPlannerResultsShowsAutoGeneratedSeedSummary() {
  const plannerResults = loadPlannerResultsModule({
    window: {
      getComputedStyle() {
        return {
          getPropertyValue() {
            return "";
          },
          paddingLeft: "0",
          paddingTop: "0"
        };
      }
    },
    context: {
      document: {
        createElement() {
          return createFakeDomElement();
        }
      }
    }
  });
  const autoStage = {
    requestedOptimizer: "auto",
    activeStage: "cp-sat",
    stageIndex: 3,
    cycleIndex: 1,
    consecutiveWeakCycles: 0,
    lastCycleImprovementRatio: 0.1,
    stopReason: "completed-plan",
    generatedSeeds: [
      { stage: "greedy", stageIndex: 1, cycleIndex: 0, randomSeed: 11 },
      { stage: "lns", stageIndex: 2, cycleIndex: 1, randomSeed: 13 },
      { stage: "cp-sat", stageIndex: 3, cycleIndex: 1, randomSeed: 17 }
    ]
  };
  const state = {
    isSolving: false,
    grid: [[1, 1]],
    result: {
      solution: {
        optimizer: "auto",
        activeOptimizer: "cp-sat",
        autoStage,
        roads: ["0,0"],
        services: [],
        serviceTypeIndices: [],
        servicePopulationIncreases: [],
        residentials: [],
        residentialTypeIndices: [],
        populations: [],
        totalPopulation: 0
      },
      stats: {
        optimizer: "auto",
        activeOptimizer: "cp-sat",
        autoStage,
        manualLayout: false,
        cpSatStatus: null,
        stoppedByUser: false,
        stoppedByTimeLimit: false,
        totalPopulation: 0,
        roadCount: 1,
        serviceCount: 0,
        residentialCount: 0
      },
      validation: {
        valid: true,
        errors: []
      }
    },
    resultContext: {
      grid: [[1, 1]],
      params: {
        optimizer: "auto",
        cpSat: { randomSeed: 999 },
        serviceTypes: [],
        residentialTypes: []
      }
    },
    solveProgressLog: [],
    resultIsLiveSnapshot: false,
    resultError: "",
    resultElapsedMs: 1000,
    selectedMapBuilding: null,
    selectedMapCell: null,
    layoutEditor: {
      mode: "inspect",
      pendingPlacement: null,
      isApplying: false,
      edited: false,
      pendingValidation: false,
      status: ""
    }
  };
  const elements = new Proxy(
    {},
    {
      get(target, key) {
        if (!target[key]) target[key] = createFakeDomElement();
        return target[key];
      }
    }
  );
  const controller = plannerResults.createPlannerResultsController({
    state,
    elements,
    helpers: {
      cloneJson(value) {
        return JSON.parse(JSON.stringify(value));
      },
      formatElapsedTime(value) {
        return `${value}ms`;
      }
    },
    callbacks: {
      applyMatrixLayout() {},
      clearExpansionAdvice() {},
      getOptimizerLabel(value) {
        return value === "cp-sat" ? "CP-SAT" : value === "auto" ? "Auto" : String(value);
      },
      renderExpansionAdvice() {},
      setSolveState() {},
      syncActionAvailability() {}
    }
  });

  controller.renderResults();

  assert.match(elements.resultSolverStatus.textContent, /Auto -> CP-SAT/);
  assert.match(elements.resultSolverStatus.textContent, /generated 3 stage seeds/);
  assert.match(elements.resultSolverStatus.textContent, /latest CP-SAT 17/);
  assert.doesNotMatch(elements.resultSolverStatus.textContent, /999/);
}

function testPlannerResultsShowsGreedyDiagnosticsReport() {
  function createRecordingElement(overrides = {}) {
    return createFakeDomElement({
      children: [],
      append(...children) {
        this.children.push(...children);
      },
      appendChild(child) {
        this.children.push(child);
      },
      ...overrides
    });
  }

  const plannerResults = loadPlannerResultsModule({
    window: {
      getComputedStyle() {
        return {
          getPropertyValue() {
            return "";
          },
          paddingLeft: "0",
          paddingTop: "0"
        };
      }
    },
    context: {
      document: {
        createElement() {
          return createRecordingElement();
        }
      }
    }
  });
  const state = {
    isSolving: false,
    grid: [
      [1, 1],
      [1, 1]
    ],
    result: {
      solution: {
        optimizer: "greedy",
        roads: [],
        services: [],
        serviceTypeIndices: [],
        servicePopulationIncreases: [],
        residentials: [],
        residentialTypeIndices: [],
        populations: [],
        totalPopulation: 0,
        greedyDiagnostics: {
          version: 1,
          candidateLimit: 2000,
          examplesPerReason: 3,
          services: {
            candidateLimit: 2000,
            candidatesScanned: 1,
            candidatesSkippedAsPlaced: 0,
            truncated: false,
            placedCount: 0,
            overallAvailability: { limit: null, used: 0, remaining: null },
            availabilityByType: [],
            reasonCounts: { "no-service-coverage": 1 },
            examplesByReason: {
              "no-service-coverage": [
                {
                  kind: "service",
                  reason: "no-service-coverage",
                  reasons: ["no-service-coverage"],
                  r: 0,
                  c: 0,
                  rows: 1,
                  cols: 1,
                  typeIndex: 0,
                  typeName: "Clinic",
                  score: 0
                }
              ]
            }
          },
          residentials: {
            candidateLimit: 2000,
            candidatesScanned: 1,
            candidatesSkippedAsPlaced: 0,
            truncated: false,
            placedCount: 0,
            overallAvailability: { limit: null, used: 0, remaining: null },
            availabilityByType: [],
            reasonCounts: { "base-only": 1 },
            examplesByReason: {
              "base-only": [
                {
                  kind: "residential",
                  reason: "base-only",
                  reasons: ["base-only"],
                  r: 0,
                  c: 0,
                  rows: 1,
                  cols: 1,
                  typeIndex: 0,
                  typeName: "House",
                  population: 10,
                  basePopulation: 10
                }
              ]
            }
          }
        }
      },
      stats: {
        optimizer: "greedy",
        manualLayout: false,
        cpSatStatus: null,
        stoppedByUser: false,
        stoppedByTimeLimit: false,
        totalPopulation: 0,
        roadCount: 0,
        serviceCount: 0,
        residentialCount: 0
      },
      validation: {
        valid: true,
        errors: []
      }
    },
    resultContext: {
      grid: [
        [1, 1],
        [1, 1]
      ],
      params: {
        optimizer: "greedy",
        serviceTypes: [{ name: "Clinic", bonus: 10, rows: 1, cols: 1, range: 1, avail: 1 }],
        residentialTypes: [{ name: "House", w: 1, h: 1, min: 10, max: 20, avail: 1 }]
      }
    },
    solveProgressLog: [],
    resultIsLiveSnapshot: false,
    resultError: "",
    resultElapsedMs: 1000,
    selectedMapBuilding: null,
    selectedMapCell: null,
    layoutEditor: {
      mode: "inspect",
      pendingPlacement: null,
      isApplying: false,
      edited: false,
      pendingValidation: false,
      status: ""
    }
  };
  const elements = new Proxy(
    {},
    {
      get(target, key) {
        if (!target[key]) target[key] = createRecordingElement();
        return target[key];
      }
    }
  );
  const controller = plannerResults.createPlannerResultsController({
    state,
    elements,
    helpers: {
      cloneJson(value) {
        return JSON.parse(JSON.stringify(value));
      },
      formatElapsedTime(value) {
        return `${value}ms`;
      }
    },
    callbacks: {
      applyMatrixLayout() {},
      clearExpansionAdvice() {},
      getOptimizerLabel(value) {
        return value === "greedy" ? "Greedy" : String(value);
      },
      renderExpansionAdvice() {},
      setSolveState() {},
      syncActionAvailability() {}
    }
  });

  controller.renderResults();

  assert.equal(elements.greedyDiagnosticsBlock.hidden, false);
  assert.match(elements.greedyDiagnosticsSummary.textContent, /1 unplaced service candidates/);
  assert.equal(elements.greedyDiagnosticsServiceList.children.length, 1);
  assert.equal(elements.greedyDiagnosticsResidentialList.children.length, 1);
  assert.match(elements.greedyDiagnosticsServiceList.children[0].children[0].textContent, /No service coverage: 1/);
  assert.match(
    elements.greedyDiagnosticsResidentialList.children[0].children[0].textContent,
    /Base population only: 1/
  );
}

function runPlannerResultsStatusDiagnosticsTests() {
  testPlannerResultsShowsAutoGeneratedSeedSummary();
  testPlannerResultsShowsGreedyDiagnosticsReport();
}

module.exports = { runPlannerResultsStatusDiagnosticsTests };
