/**
 * @param {Window & { CityBuilderAppElements?: unknown }} globalObject
 */
(function attachPlannerAppElements(globalObject) {
  /**
   * @typedef {Record<string, Element | null>} PlannerAppElements
   */

  /**
   * @param {Document} documentObject
   * @returns {PlannerAppElements}
   */
  function createPlannerAppElements(documentObject) {
    return {
      gridRows: documentObject.querySelector("#gridRows"),
      gridCols: documentObject.querySelector("#gridCols"),
      gridEditor: documentObject.querySelector("#gridEditor"),
      gridStats: documentObject.querySelector("#gridStats"),
      paintModeToggle: documentObject.querySelector("#paintModeToggle"),
      sampleProblemButtons: documentObject.querySelector("#sampleProblemButtons"),
      solverToggle: documentObject.querySelector("#solverToggle"),
      runtimePresetButtons: documentObject.querySelector("#runtimePresetButtons"),
      runtimePresetStatus: documentObject.querySelector("#runtimePresetStatus"),
      advancedModeToggle: documentObject.querySelector("#advancedModeToggle"),
      cpSatReadinessStatus: documentObject.querySelector("#cpSatReadinessStatus"),
      autoPanel: documentObject.querySelector("#autoPanel"),
      autoWallClockLimitSeconds: documentObject.querySelector("#autoWallClockLimitSeconds"),
      autoContinueAfterPopulationCapSeconds: documentObject.querySelector("#autoContinueAfterPopulationCapSeconds"),
      autoPopulationCapGracePresetButton: documentObject.querySelector("#autoPopulationCapGracePresetButton"),
      greedyPanel: documentObject.querySelector("#greedyPanel"),
      lnsPanel: documentObject.querySelector("#lnsPanel"),
      cpSatPanel: documentObject.querySelector("#cpSatPanel"),
      maxServices: documentObject.querySelector("#maxServices"),
      maxResidentials: documentObject.querySelector("#maxResidentials"),
      catalogImportText: documentObject.querySelector("#catalogImportText"),
      importCatalogTextButton: documentObject.querySelector("#importCatalogTextButton"),
      catalogImportStatus: documentObject.querySelector("#catalogImportStatus"),
      addServiceTypeButton: documentObject.querySelector("#addServiceTypeButton"),
      addResidentialTypeButton: documentObject.querySelector("#addResidentialTypeButton"),
      serviceList: documentObject.querySelector("#serviceList"),
      residentialList: documentObject.querySelector("#residentialList"),
      solveButton: documentObject.querySelector("#solveButton"),
      stopSolveButton: documentObject.querySelector("#stopSolveButton"),
      solveStatus: documentObject.querySelector("#solveStatus"),
      solveTimer: documentObject.querySelector("#solveTimer"),
      configStorageName: documentObject.querySelector("#configStorageName"),
      saveConfigButton: documentObject.querySelector("#saveConfigButton"),
      savedConfigsSelect: documentObject.querySelector("#savedConfigsSelect"),
      loadConfigButton: documentObject.querySelector("#loadConfigButton"),
      exportConfigsButton: documentObject.querySelector("#exportConfigsButton"),
      importConfigsButton: documentObject.querySelector("#importConfigsButton"),
      configImportFileInput: documentObject.querySelector("#configImportFileInput"),
      deleteConfigButton: documentObject.querySelector("#deleteConfigButton"),
      configStorageStatus: documentObject.querySelector("#configStorageStatus"),
      payloadPreview: documentObject.querySelector("#payloadPreview"),
      summaryGridSize: documentObject.querySelector("#summaryGridSize"),
      summaryAllowedCells: documentObject.querySelector("#summaryAllowedCells"),
      summaryServiceTypes: documentObject.querySelector("#summaryServiceTypes"),
      summaryResidentialTypes: documentObject.querySelector("#summaryResidentialTypes"),
      summaryOptimizer: documentObject.querySelector("#summaryOptimizer"),
      resultsEmpty: documentObject.querySelector("#resultsEmpty"),
      resultsContent: documentObject.querySelector("#resultsContent"),
      resultBadge: documentObject.querySelector("#resultBadge"),
      validationNotice: documentObject.querySelector("#validationNotice"),
      resultPopulation: documentObject.querySelector("#resultPopulation"),
      resultRoadCount: documentObject.querySelector("#resultRoadCount"),
      resultServiceCount: documentObject.querySelector("#resultServiceCount"),
      resultResidentialCount: documentObject.querySelector("#resultResidentialCount"),
      resultElapsed: documentObject.querySelector("#resultElapsed"),
      resultSolverStatus: documentObject.querySelector("#resultSolverStatus"),
      resultProgressSummary: documentObject.querySelector("#resultProgressSummary"),
      resultProgressLog: documentObject.querySelector("#resultProgressLog"),
      expansionNextService: documentObject.querySelector("#expansionNextService"),
      expansionNextResidential: documentObject.querySelector("#expansionNextResidential"),
      compareExpansionButton: documentObject.querySelector("#compareExpansionButton"),
      expansionAdviceStatus: documentObject.querySelector("#expansionAdviceStatus"),
      expansionAdviceMetrics: documentObject.querySelector("#expansionAdviceMetrics"),
      expansionAdviceWinner: documentObject.querySelector("#expansionAdviceWinner"),
      expansionAdviceBaseline: documentObject.querySelector("#expansionAdviceBaseline"),
      expansionAdviceServiceOutcome: documentObject.querySelector("#expansionAdviceServiceOutcome"),
      expansionAdviceResidentialOutcome: documentObject.querySelector("#expansionAdviceResidentialOutcome"),
      serviceResultList: documentObject.querySelector("#serviceResultList"),
      residentialResultList: documentObject.querySelector("#residentialResultList"),
      remainingServiceList: documentObject.querySelector("#remainingServiceList"),
      remainingResidentialList: documentObject.querySelector("#remainingResidentialList"),
      resultMapGrid: documentObject.querySelector("#resultMapGrid"),
      resultOverlay: documentObject.querySelector("#resultOverlay"),
      resultHeatmapToggle: documentObject.querySelector("#resultHeatmapToggle"),
      resultExplainabilityModeToggle: documentObject.querySelector("#resultExplainabilityModeToggle"),
      layoutEditModeToggle: documentObject.querySelector("#layoutEditModeToggle"),
      rotatePendingPlacementButton: documentObject.querySelector("#rotatePendingPlacementButton"),
      validateEditedLayoutButton: documentObject.querySelector("#validateEditedLayoutButton"),
      layoutEditorStatus: documentObject.querySelector("#layoutEditorStatus"),
      selectedBuildingTitle: documentObject.querySelector("#selectedBuildingTitle"),
      selectedBuildingSummary: documentObject.querySelector("#selectedBuildingSummary"),
      moveSelectedBuildingButton: documentObject.querySelector("#moveSelectedBuildingButton"),
      removeSelectedBuildingButton: documentObject.querySelector("#removeSelectedBuildingButton"),
      selectedBuildingFacts: documentObject.querySelector("#selectedBuildingFacts"),
      selectedBuildingId: documentObject.querySelector("#selectedBuildingId"),
      selectedBuildingCategory: documentObject.querySelector("#selectedBuildingCategory"),
      selectedBuildingPosition: documentObject.querySelector("#selectedBuildingPosition"),
      selectedBuildingFootprint: documentObject.querySelector("#selectedBuildingFootprint"),
      selectedBuildingEffect: documentObject.querySelector("#selectedBuildingEffect"),
      selectedBuildingAvailability: documentObject.querySelector("#selectedBuildingAvailability"),
      layoutStorageName: documentObject.querySelector("#layoutStorageName"),
      saveLayoutButton: documentObject.querySelector("#saveLayoutButton"),
      savedLayoutsSelect: documentObject.querySelector("#savedLayoutsSelect"),
      loadLayoutButton: documentObject.querySelector("#loadLayoutButton"),
      exportLayoutsButton: documentObject.querySelector("#exportLayoutsButton"),
      importLayoutsButton: documentObject.querySelector("#importLayoutsButton"),
      layoutImportFileInput: documentObject.querySelector("#layoutImportFileInput"),
      deleteLayoutButton: documentObject.querySelector("#deleteLayoutButton"),
      layoutStorageStatus: documentObject.querySelector("#layoutStorageStatus"),
      greedyLocalSearch: documentObject.querySelector("#greedyLocalSearch"),
      greedyRandomSeed: documentObject.querySelector("#greedyRandomSeed"),
      greedyTimeLimitSeconds: documentObject.querySelector("#greedyTimeLimitSeconds"),
      greedyProfile: documentObject.querySelector("#greedyProfile"),
      greedyDensityTieBreaker: documentObject.querySelector("#greedyDensityTieBreaker"),
      greedyDensityTieBreakerTolerancePercent: documentObject.querySelector("#greedyDensityTieBreakerTolerancePercent"),
      greedyRestarts: documentObject.querySelector("#greedyRestarts"),
      greedyServiceRefineIterations: documentObject.querySelector("#greedyServiceRefineIterations"),
      greedyServiceRefineCandidateLimit: documentObject.querySelector("#greedyServiceRefineCandidateLimit"),
      greedyExhaustiveServiceSearch: documentObject.querySelector("#greedyExhaustiveServiceSearch"),
      greedyDiagnostics: documentObject.querySelector("#greedyDiagnostics"),
      greedyServiceExactPoolLimit: documentObject.querySelector("#greedyServiceExactPoolLimit"),
      greedyServiceExactMaxCombinations: documentObject.querySelector("#greedyServiceExactMaxCombinations"),
      greedyDiagnosticsBlock: documentObject.querySelector("#greedyDiagnosticsBlock"),
      greedyDiagnosticsSummary: documentObject.querySelector("#greedyDiagnosticsSummary"),
      greedyDiagnosticsServiceList: documentObject.querySelector("#greedyDiagnosticsServiceList"),
      greedyDiagnosticsResidentialList: documentObject.querySelector("#greedyDiagnosticsResidentialList"),
      lnsIterations: documentObject.querySelector("#lnsIterations"),
      lnsMaxNoImprovementIterations: documentObject.querySelector("#lnsMaxNoImprovementIterations"),
      lnsNeighborhoodRows: documentObject.querySelector("#lnsNeighborhoodRows"),
      lnsNeighborhoodCols: documentObject.querySelector("#lnsNeighborhoodCols"),
      lnsRepairTimeLimitSeconds: documentObject.querySelector("#lnsRepairTimeLimitSeconds"),
      lnsUseDisplayedSeed: documentObject.querySelector("#lnsUseDisplayedSeed"),
      cpSatTimeLimitSeconds: documentObject.querySelector("#cpSatTimeLimitSeconds"),
      cpSatNoImprovementTimeoutSeconds: documentObject.querySelector("#cpSatNoImprovementTimeoutSeconds"),
      cpSatRandomSeed: documentObject.querySelector("#cpSatRandomSeed"),
      cpSatNumWorkers: documentObject.querySelector("#cpSatNumWorkers"),
      cpSatLogSearchProgress: documentObject.querySelector("#cpSatLogSearchProgress"),
      cpSatUseDisplayedHint: documentObject.querySelector("#cpSatUseDisplayedHint"),
      cpSatPortfolioEnabled: documentObject.querySelector("#cpSatPortfolioEnabled"),
      cpSatPortfolioWorkerCount: documentObject.querySelector("#cpSatPortfolioWorkerCount"),
      cpSatPortfolioRandomSeeds: documentObject.querySelector("#cpSatPortfolioRandomSeeds"),
      cpSatPortfolioPerWorkerTimeLimitSeconds: documentObject.querySelector("#cpSatPortfolioPerWorkerTimeLimitSeconds"),
      cpSatPortfolioPerWorkerNumWorkers: documentObject.querySelector("#cpSatPortfolioPerWorkerNumWorkers"),
      cpSatPortfolioRandomizeSearch: documentObject.querySelector("#cpSatPortfolioRandomizeSearch"),
      lnsSeedStatus: documentObject.querySelector("#lnsSeedStatus"),
      cpSatHintStatus: documentObject.querySelector("#cpSatHintStatus"),
      resizeGridButton: documentObject.querySelector("#resizeGridButton"),
      fillAllowedButton: documentObject.querySelector("#fillAllowedButton"),
      clearGridButton: documentObject.querySelector("#clearGridButton"),
      sampleGridButton: documentObject.querySelector("#sampleGridButton")
    };
  }

  const appElementsGlobal = /** @type {Window & { CityBuilderAppElements?: unknown }} */ (globalObject);
  appElementsGlobal.CityBuilderAppElements = Object.freeze({
    createPlannerAppElements
  });
})(window);
