const assert = require("node:assert/strict");
const childProcess = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const {
  buildCpSatBenchmarkCpuPlan,
  buildExperimentRegistryEntry,
  buildLearnedRankingLabelFingerprint,
  buildLearnedRankingLabelRegistryEntryDraft,
  buildLearnedRankingLabelTelemetryManifest,
  buildLnsReplayLabelScaleReadiness,
  buildGreedyOfflineRankerRegistryEntryDraft,
  buildGreedyOfflineRankerTelemetryManifest,
  buildLnsWindowRankerBaselineRegistryEntryDraft,
  buildLnsWindowRankerBaselineTelemetryManifest,
  collectGreedyOrderingLabelsFromBenchmarkSuite,
  createGreedyOfflineRankerSnapshot,
  createLearnedRankingLabelSnapshot,
  createLnsWindowRankerBaselineSnapshot,
  DEFAULT_DETERMINISTIC_ABLATION_GATE_SEEDS,
  DEFAULT_LEARNED_RANKING_LABEL_SPLITS,
  STRICT_LNS_REPLAY_LABEL_PRESET,
  STRICT_LNS_REPLAY_LABEL_SCALE_THRESHOLDS,
  STRICT_LNS_REPLAY_LABEL_SEEDS,
  STRICT_LNS_REPLAY_LABEL_STATE_POLICIES,
  DEFAULT_LNS_REPLAY_LABEL_CASE_NAMES,
  DEFAULT_LNS_REPLAY_LABEL_CORPUS,
  DEFAULT_LNS_REPLAY_LABEL_SCALE_THRESHOLDS,
  createGreedyConnectivityShadowOrderingLabelSnapshot,
  createLnsBenchmarkSnapshot,
  createLnsNeighborhoodAblationSnapshot,
  createLnsWindowReplaySnapshot,
  DEFAULT_LNS_BENCHMARK_CORPUS,
  DEFAULT_LNS_BENCHMARK_OPTIONS,
  DEFAULT_LNS_NEIGHBORHOOD_ABLATION_CASE_NAMES,
  DEFAULT_LNS_NEIGHBORHOOD_ABLATION_VARIANTS,
  formatGreedyConnectivityShadowOrderingLabels,
  formatGreedyOfflineRankerExperiment,
  formatLearnedRankingLabelSuite,
  formatLnsNeighborhoodAblation,
  formatLnsBenchmarkSuite,
  formatLnsWindowRankerBaselineExperiment,
  formatLnsWindowReplayLabels,
  listGreedyConnectivityShadowOrderingLabelCaseNames,
  listLnsReplayPressureFamilies,
  listLnsNeighborhoodAblationCaseNames,
  listLnsBenchmarkCaseNames,
  listLnsWindowReplayCaseNames,
  normalizeLnsBenchmarkOptions,
  runGreedyConnectivityShadowOrderingLabels,
  runGreedyOfflineRankerExperiment,
  runLearnedRankingLabelSuite,
  runLnsWindowRankerBaselineExperiment,
  runLnsNeighborhoodAblation,
  runLnsWindowReplayLabels,
  runLnsBenchmarkSuite,
  DEFAULT_GREEDY_BENCHMARK_CORPUS,
  DEFAULT_CP_SAT_BENCHMARK_CORPUS,
  DEFAULT_CP_SAT_BENCHMARK_OPTIONS,
  DEFAULT_CP_SAT_ROAD_SEMANTICS_SCORECARD_CASE_NAMES,
  formatCpSatBenchmarkSuite,
  listCpSatBenchmarkCaseNames,
  normalizeCpSatBenchmarkOptions,
  runCpSatBenchmarkSuite,
  validateExperimentRegistryEntry
} = require("city-builder/benchmarks");

const {
  OMITTED_SOLVER_OPTIMIZER,
  RECOMMENDED_INTERACTIVE_OPTIMIZER,
  getOptimizerAdapter,
  listOptimizerAdapters,
  resolveOptimizerName,
  buildDecisionTraceFromSolution,
  solve,
  solveAsync,
  solveAuto,
  solveGreedy,
  solveCpSat,
  solveCpSatAsync,
  solveLns,
  startAutoSolve,
  startCpSatSolve,
  evaluateLayout,
  validateLayoutConstraints,
  validateSolution
} = require("city-builder/solver");
const { delay, resolveCpSatPython, waitForFile, waitForHeartbeatToStop } = require("../helpers/processHelpers.cjs");
const { buildMockSolution } = require("../helpers/solverFixtures.cjs");
const { runGreedyValidationOptimizerTests } = require("./greedyValidationAssertions.cjs");
const { materializeCpSatSolution, parseCpSatRawSolution } = require("../../dist/packages/solvers/cp-sat/solver.js");
const {
  buildAdaptiveNeighborhoodCandidates,
  buildLnsWarmStartHint,
  buildNeighborhoodWindows
} = require("../../dist/packages/solvers/lns/solver.js");
const { repairSmallWindowWithDp } = require("../../dist/packages/solvers/lns/smallWindowDpRepair.js");
const { startJsonBackgroundSolve } = require("../../dist/packages/runtime/index.js");
const { applyDeterministicDominanceUpgrades } = require("../../dist/packages/core/dominanceUpgrades.js");
const { buildPlannerExplainabilityMap } = require("../../dist/packages/core/plannerExplainability.js");
const { computePopulationCapacityUpperBound } = require("../../dist/packages/core/populationBounds.js");
const { createCpSatPythonHelperAssertions } = require("./cpSatPythonHelperAssertions.cjs");
const { GreedyAttemptState } = require("../../dist/packages/solvers/greedy/attemptState.js");
const {
  createRoadOpportunityRecorder,
  recordRoadOpportunityPlacementFromOccupiedBuildings
} = require("../../dist/packages/solvers/greedy/roadOpportunity.js");
const {
  runGreedyServiceMasterDecomposition
} = require("../../dist/packages/solvers/greedy/serviceMasterDecomposition.js");
const { serviceCandidateKey } = require("../../dist/packages/solvers/greedy/candidates.js");
const { createGreedyProfileCounters } = require("../../dist/packages/solvers/greedy/profile.js");
const {
  computeRoadAnchorReachableEmptyFrontier,
  createRoadProbeScratch,
  measureBuildingConnectivityShadow,
  measureBuildingConnectivityShadowFromFrontier,
  pruneRedundantRoads,
  probeBuildingConnectedToRoads,
  roadAnchorSeedCandidates,
  roadAnchorRepresentativeSeedCandidates
} = require("../../dist/packages/core/roads.js");
const {
  forEachRectangleBorderCell,
  forEachRectangleCell,
  rectangleBorderCells,
  rectangleCells
} = require("../../dist/packages/core/grid.js");
const {
  buildFootprintGeometryCache,
  buildServiceGeometryCache,
  buildServiceEffectZoneSet,
  countServiceBoost,
  isBoostedByService,
  overlaps,
  residentialFootprint,
  serviceEffectZone,
  serviceFootprint
} = require("../../dist/packages/core/buildings.js");
const {
  maybeTestCpSatBorderAccessCapacityHelpers,
  maybeTestCpSatAllowsMultipleAnchoredRoadComponents,
  maybeTestCpSatCandidateReductionHelpers,
  maybeTestCpSatConnectivityHelperConstraints,
  maybeTestCpSatDisallowsBidirectionalRoadFlow,
  maybeTestCpSatGateRegionalCapacityHelpers,
  maybeTestCpSatGateRequirementHelpers,
  maybeTestCpSatPopulationUpperBoundHelpers,
  maybeTestCpSatPrunesObjectivelyUselessServices,
  maybeTestCpSatReachabilityReductionHelpers,
  maybeTestCpSatResidentialPopulationUpperBoundHelpers,
  maybeTestCpSatRoadEligibilityReductionHelpers
} = createCpSatPythonHelperAssertions(resolveCpSatPython);

const {
  runGreedyBenchmarkSetupAssertions,
  runGreedyServiceLookaheadOptimizerAssertions
} = require("./greedyBenchmarkSetupAssertions.cjs");
const {
  runGreedyBenchmarkOptimizerAssertions,
  runGreedyBenchmarkRegressionAssertions
} = require("./greedyBenchmarkRegressionAssertions.cjs");

module.exports = {
  assert,
  childProcess,
  fs,
  os,
  path,
  buildCpSatBenchmarkCpuPlan,
  buildExperimentRegistryEntry,
  buildLearnedRankingLabelFingerprint,
  buildLearnedRankingLabelRegistryEntryDraft,
  buildLearnedRankingLabelTelemetryManifest,
  buildLnsReplayLabelScaleReadiness,
  buildGreedyOfflineRankerRegistryEntryDraft,
  buildGreedyOfflineRankerTelemetryManifest,
  buildLnsWindowRankerBaselineRegistryEntryDraft,
  buildLnsWindowRankerBaselineTelemetryManifest,
  collectGreedyOrderingLabelsFromBenchmarkSuite,
  createGreedyOfflineRankerSnapshot,
  createLearnedRankingLabelSnapshot,
  createLnsWindowRankerBaselineSnapshot,
  DEFAULT_DETERMINISTIC_ABLATION_GATE_SEEDS,
  DEFAULT_LEARNED_RANKING_LABEL_SPLITS,
  STRICT_LNS_REPLAY_LABEL_PRESET,
  STRICT_LNS_REPLAY_LABEL_SCALE_THRESHOLDS,
  STRICT_LNS_REPLAY_LABEL_SEEDS,
  STRICT_LNS_REPLAY_LABEL_STATE_POLICIES,
  DEFAULT_LNS_REPLAY_LABEL_CASE_NAMES,
  DEFAULT_LNS_REPLAY_LABEL_CORPUS,
  DEFAULT_LNS_REPLAY_LABEL_SCALE_THRESHOLDS,
  createGreedyConnectivityShadowOrderingLabelSnapshot,
  createLnsBenchmarkSnapshot,
  createLnsNeighborhoodAblationSnapshot,
  createLnsWindowReplaySnapshot,
  DEFAULT_LNS_BENCHMARK_CORPUS,
  DEFAULT_LNS_BENCHMARK_OPTIONS,
  DEFAULT_LNS_NEIGHBORHOOD_ABLATION_CASE_NAMES,
  DEFAULT_LNS_NEIGHBORHOOD_ABLATION_VARIANTS,
  formatGreedyConnectivityShadowOrderingLabels,
  formatGreedyOfflineRankerExperiment,
  formatLearnedRankingLabelSuite,
  formatLnsNeighborhoodAblation,
  formatLnsBenchmarkSuite,
  formatLnsWindowRankerBaselineExperiment,
  formatLnsWindowReplayLabels,
  listGreedyConnectivityShadowOrderingLabelCaseNames,
  listLnsReplayPressureFamilies,
  listLnsNeighborhoodAblationCaseNames,
  listLnsBenchmarkCaseNames,
  listLnsWindowReplayCaseNames,
  normalizeLnsBenchmarkOptions,
  runGreedyConnectivityShadowOrderingLabels,
  runGreedyOfflineRankerExperiment,
  runLearnedRankingLabelSuite,
  runLnsWindowRankerBaselineExperiment,
  runLnsNeighborhoodAblation,
  runLnsWindowReplayLabels,
  runLnsBenchmarkSuite,
  DEFAULT_GREEDY_BENCHMARK_CORPUS,
  DEFAULT_CP_SAT_BENCHMARK_CORPUS,
  DEFAULT_CP_SAT_BENCHMARK_OPTIONS,
  DEFAULT_CP_SAT_ROAD_SEMANTICS_SCORECARD_CASE_NAMES,
  formatCpSatBenchmarkSuite,
  listCpSatBenchmarkCaseNames,
  normalizeCpSatBenchmarkOptions,
  runCpSatBenchmarkSuite,
  validateExperimentRegistryEntry,
  OMITTED_SOLVER_OPTIMIZER,
  RECOMMENDED_INTERACTIVE_OPTIMIZER,
  getOptimizerAdapter,
  listOptimizerAdapters,
  resolveOptimizerName,
  buildDecisionTraceFromSolution,
  solve,
  solveAsync,
  solveAuto,
  solveGreedy,
  solveCpSat,
  solveCpSatAsync,
  solveLns,
  startAutoSolve,
  startCpSatSolve,
  evaluateLayout,
  validateLayoutConstraints,
  validateSolution,
  delay,
  resolveCpSatPython,
  waitForFile,
  waitForHeartbeatToStop,
  buildMockSolution,
  runGreedyValidationOptimizerTests,
  materializeCpSatSolution,
  parseCpSatRawSolution,
  buildAdaptiveNeighborhoodCandidates,
  buildLnsWarmStartHint,
  buildNeighborhoodWindows,
  repairSmallWindowWithDp,
  startJsonBackgroundSolve,
  applyDeterministicDominanceUpgrades,
  buildPlannerExplainabilityMap,
  computePopulationCapacityUpperBound,
  GreedyAttemptState,
  createRoadOpportunityRecorder,
  recordRoadOpportunityPlacementFromOccupiedBuildings,
  runGreedyServiceMasterDecomposition,
  serviceCandidateKey,
  createGreedyProfileCounters,
  computeRoadAnchorReachableEmptyFrontier,
  createRoadProbeScratch,
  measureBuildingConnectivityShadow,
  measureBuildingConnectivityShadowFromFrontier,
  pruneRedundantRoads,
  probeBuildingConnectedToRoads,
  roadAnchorSeedCandidates,
  roadAnchorRepresentativeSeedCandidates,
  forEachRectangleBorderCell,
  forEachRectangleCell,
  rectangleBorderCells,
  rectangleCells,
  buildFootprintGeometryCache,
  buildServiceGeometryCache,
  buildServiceEffectZoneSet,
  countServiceBoost,
  isBoostedByService,
  overlaps,
  residentialFootprint,
  serviceEffectZone,
  serviceFootprint,
  maybeTestCpSatBorderAccessCapacityHelpers,
  maybeTestCpSatAllowsMultipleAnchoredRoadComponents,
  maybeTestCpSatCandidateReductionHelpers,
  maybeTestCpSatConnectivityHelperConstraints,
  maybeTestCpSatDisallowsBidirectionalRoadFlow,
  maybeTestCpSatGateRegionalCapacityHelpers,
  maybeTestCpSatGateRequirementHelpers,
  maybeTestCpSatPopulationUpperBoundHelpers,
  maybeTestCpSatPrunesObjectivelyUselessServices,
  maybeTestCpSatReachabilityReductionHelpers,
  maybeTestCpSatResidentialPopulationUpperBoundHelpers,
  maybeTestCpSatRoadEligibilityReductionHelpers,
  runGreedyBenchmarkSetupAssertions,
  runGreedyServiceLookaheadOptimizerAssertions,
  runGreedyBenchmarkOptimizerAssertions,
  runGreedyBenchmarkRegressionAssertions
};
