/**
 * Public solver and domain API.
 *
 * Prefer this entry point for application/runtime consumers. The root
 * `src/index.ts` remains a compatibility facade while benchmark and experiment
 * tooling move behind their own public API.
 */

export { solve, solveAsync } from "./runtime/solve.js";
export { describeAutoStopReason, solveAuto, startAutoSolve } from "./auto/index.js";
export { solveGreedy } from "./greedy/solver.js";
export { solveCpSat, solveCpSatAsync, startCpSatSolve } from "./cp-sat/solver.js";
export { solveLns } from "./lns/solver.js";
export {
  assertValidLayout,
  assertValidLayoutConstraints,
  buildDecisionTraceFromSolution,
  buildEmptySolverProgressSummary,
  buildSolverProgressSummary,
  buildTimeToQualityScorecard,
  evaluateLayout,
  formatSolutionMap,
  formatLayoutEvaluationErrors,
  formatLayoutValidationErrors,
  formatSolverProgressSummary,
  formatTimeToQualityScorecard,
  buildPlannerExplainabilityMap,
  parseDecisionTraceJsonl,
  renderSolutionMap,
  serializeDecisionTraceJsonl,
  summarizeDecisionTraceReason,
  validateLayoutConstraints,
  validateSolution,
  validateSolutionMap,
} from "./core/index.js";
export { CP_SAT_PORTFOLIO_CAPABILITY_LIMITS, OMITTED_SOLVER_OPTIMIZER, RECOMMENDED_INTERACTIVE_OPTIMIZER } from "./core/index.js";
export { getOptimizerAdapter, listOptimizerAdapters, resolveOptimizerName } from "./runtime/optimizerRegistry.js";

export type {
  BuildDecisionTraceOptions,
  BuildTimeToQualityScorecardOptions,
  Grid,
  BackgroundSolveHandle,
  BackgroundSolveSnapshotState,
  OptimizerName,
  AutoOptions,
  AutoStageOptimizerName,
  AutoSolveStopReason,
  AutoSolveGeneratedSeed,
  AutoSolveStageMetadata,
  CpSatOptions,
  CpSatObjectivePolicy,
  CpSatPortfolioCapabilityLimits,
  CpSatTelemetry,
  CpSatPortfolioOptions,
  CpSatPortfolioSummary,
  CpSatPortfolioWorkerSummary,
  CpSatProgressKind,
  CpSatProgressUpdate,
  CpSatAsyncOptions,
  CpSatWarmStartHint,
  CpSatWarmStartServicePlacement,
  CpSatWarmStartResidentialPlacement,
  GreedyOptions,
  GreedyDiagnostics,
  GreedyDiagnosticAvailabilityEntry,
  GreedyDiagnosticExample,
  GreedyDiagnosticKindReport,
  GreedyDiagnosticOverallAvailability,
  GreedyPlacementDiagnosticReason,
  GreedyProfile,
  GreedyProfileCounters,
  GreedyProfilePhaseName,
  GreedyProfilePhaseSummary,
  LnsNeighborhoodAnchorPolicy,
  LnsOptions,
  CpSatNeighborhoodWindow,
  SolverParams,
  Solution,
  SerializedSolution,
  SolveRequestPayload,
  SolveResponseStats,
  SolveResponseValidation,
  SolveResponsePayload,
  PlannerExplainabilityCell,
  PlannerExplainabilityMap,
  SolverDecisionTraceDecision,
  SolverDecisionTraceEvent,
  SolverDecisionTraceEvidenceValue,
  SolverDecisionTraceKind,
  SolverDecisionTraceScore,
  SolverDecisionTraceStage,
  SolverElapsedScoreCheckpoint,
  SolverQualityTargetCheckpoint,
  SolverProgressPortfolioSummary,
  SolverProgressSummary,
  SolverTimeToQualityScorecard,
  AvailableBuildings,
  ResidentialSettings,
  ResidentialSizeSetting,
  ResidentialTypeSetting,
  ServiceTypeSetting,
  ServiceCandidate,
  ResidentialCandidate,
  EvaluatedServicePlacement,
  LayoutEvaluationInput,
  LayoutEvaluationResult,
  EvaluatedResidentialResult,
  SolutionValidationInput,
  SolutionValidationResult,
  PersistedRoadKey,
  PersistedServiceCandidateKey,
  PersistedResidentialCandidateKey,
  CpSatContinuationModelInput,
  CpSatContinuationCompatibility,
  CpSatContinuationRuntimeDefaults,
  CpSatContinuationIncumbent,
  CpSatContinuationHintedServicePlacement,
  CpSatContinuationHintedResidentialPlacement,
  CpSatContinuationHint,
  CpSatContinuationResumePolicy,
  CpSatContinuationCheckpoint,
  SavedLayoutRecord,
  SolutionMapValidationResult,
} from "./core/index.js";
